import { TutorialLesson } from "./types";

const PANEL_HIGHLIGHT = {
  left: ".lab-floating-panel-left",
  right: ".lab-floating-panel-right",
} as const;

const SIMULATION_LESSON: TutorialLesson = {
  id: "simulation",
  title: "Simulation",
  steps: [
    {
      id: "move-node",
      targetSelector: '[data-tutorial="canvas"]',
      instruction: "Try dragging any node on the canvas to move it around.",
      trigger: "interact",
      interactEvent: "pointerup",
      delayMs: 1000,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "change-steps",
      targetSelector: '[data-tutorial="steps"]',
      instruction:
        "Change the Steps value (e.g. 200), then press Enter or click outside the field to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "change-dt",
      targetSelector: '[data-tutorial="dt"]',
      instruction:
        "Change the dt value (e.g. 0.5), then press Enter or click outside the field to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "run-simulation",
      targetSelector: '[data-tutorial="run-simulation"]',
      instruction: 'Click the "Run simulation" button to start the simulation.',
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
    {
      id: "use-timeline",
      targetSelector: '[data-tutorial="timeline"]',
      instruction: "Drag the timeline slider to scrub through the simulation results.",
      trigger: "interact",
      interactEvent: "input",
      skipPopup: true,
    },
    {
      id: "finish-lesson",
      targetSelector: '[data-tutorial="finish-lesson"]',
      highlightSelector: ".lab-floating-panel-left",
      instruction: 'Click "Finish lesson" in the left panel to complete this lesson.',
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
  ],
};

const EDITOR_LESSON: TutorialLesson = {
  id: "editor",
  title: "Editor",
  steps: [
    {
      id: "rename-system",
      targetSelector: '[data-tutorial="system-title"]',
      instruction:
        "Give your system a name. Type a new title, then press Enter or click outside to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "save-system",
      targetSelector: '[data-tutorial="save-system"]',
      instruction: 'Click "Save system" to save your system.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "add-stock",
      targetSelector: '[data-tutorial="add-stock"]',
      instruction: 'Click "+ Stock" to create a new stock node on the canvas.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "select-stock",
      targetSelector: '[data-tutorial="canvas"]',
      instruction: "Click on the stock node you just created to select it.",
      trigger: "interact",
      interactEvent: "pointerdown",
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "rename-stock",
      targetSelector: '[data-tutorial="node-name"]',
      instruction:
        "Rename the stock node. Change the name, then press Enter or click outside to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "change-quantity",
      targetSelector: '[data-tutorial="node-quantity"]',
      instruction:
        "Set the stock quantity. Enter a value, then press Enter or click outside to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "change-color",
      targetSelector: '[data-tutorial="stock-color"]',
      instruction: "Pick a color for the stock by clicking one of the color swatches.",
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "add-flow",
      targetSelector: '[data-tutorial="add-flow"]',
      instruction: 'Click "+ Flow" to add a flow node.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "select-flow",
      targetSelector: '[data-tutorial="canvas"]',
      instruction: "Click on the flow node you just created to select it.",
      trigger: "interact",
      interactEvent: "pointerdown",
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "change-bottleneck",
      targetSelector: '[data-tutorial="node-bottleneck"]',
      instruction:
        "Set the flow bottleneck value. Enter a number, then press Enter or click outside to apply.",
      trigger: "commit",
      skipPopup: true,
    },
    {
      id: "connect-inflow",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Connect the flow to the stock as an inflow: drag from the flow\u2019s output handle to the stock\u2019s input handle.",
      trigger: "edge-inflow",
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "run-sim",
      targetSelector: '[data-tutorial="run-simulation"]',
      instruction: 'Click "Run simulation" so the chart has data to display.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "show-chart",
      targetSelector: '[data-tutorial="chart"]',
      instruction: "This is the simulation chart — it shows all variables over time.",
      trigger: "timer",
      delayMs: 3000,
      skipPopup: true,
    },
    {
      id: "deselect-pane",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Click on an empty area of the canvas to deselect all nodes and see the full chart.",
      trigger: "interact",
      interactEvent: "click",
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
      skipPopup: true,
    },
    {
      id: "expand-chart",
      targetSelector: '[data-tutorial="chart-expand"]',
      instruction: 'Click "Expand" to open the chart in full screen.',
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
    {
      id: "close-chart-modal",
      targetSelector: '[data-tutorial="chart-modal"]',
      instruction: "Explore the chart, then close it when you are ready.",
      trigger: "modal-close",
      skipPopup: true,
      popupPlacement: "top",
    },
    {
      id: "finish-lesson",
      targetSelector: '[data-tutorial="finish-lesson"]',
      instruction: 'Click "Finish lesson" to complete this lesson.',
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
      noHighlight: true,
      popupPlacement: "top",
    },
  ],
};

const WORKSPACE_LESSON: TutorialLesson = {
  id: "workspace",
  title: "Workspace",
  steps: [
    {
      id: "create-new-system",
      targetSelector: '[data-tutorial="create-new-system"]',
      instruction: 'Click "Create new system" to start with a fresh canvas.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "delete-node",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Delete any node: select it and press Ctrl+X or Delete, or click the Delete button in the editor panel.",
      trigger: "node-deleted",
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
      extraHighlightSelectors: ['[data-tutorial="delete-node"]'],
      shortcutHint: "Ctrl+X, Delete",
    },
    {
      id: "copy-paste-node",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Copy and paste a node: select it and press Ctrl+C then Ctrl+V, or click the Copy button in the editor panel.",
      trigger: "node-added",
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
      extraHighlightSelectors: ['[data-tutorial="copy-node"]'],
      shortcutHint: "Ctrl+C, Ctrl+V",
    },
    {
      id: "multi-select",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Select multiple nodes at once. Try all three ways: click a node for a single selection, then hold Shift and drag an empty area to rubber-band select, or hold Ctrl (⌘ on Mac) and click several nodes one by one.",
      trigger: "interact",
      interactEvent: "fs-multi-selected",
      delayMs: 800,
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
      shortcutHint: "Shift+Drag, Ctrl+Click",
    },
    {
      id: "undo-change",
      targetSelector: '[data-tutorial="undo"]',
      instruction:
        "Click the Undo button (or press Ctrl+Z) to step back through your recent changes.",
      trigger: "interact",
      interactEvent: "click",
      delayMs: 800,
      skipPopup: true,
      shortcutHint: "Ctrl+Z",
    },
    {
      id: "redo-change",
      targetSelector: '[data-tutorial="redo"]',
      instruction:
        "Click the Redo button (or press Ctrl+Shift+Z) to re-apply what you just undid.",
      trigger: "interact",
      interactEvent: "click",
      delayMs: 800,
      skipPopup: true,
      shortcutHint: "Ctrl+Shift+Z",
    },
    {
      id: "add-comment",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        'Right-click on the canvas and select "+ Comment", then type something and click Save.',
      trigger: "comment-saved",
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "zoom-out",
      targetSelector: '[data-tutorial="zoom-out"]',
      instruction: "Click the zoom-out button three times to zoom out on the canvas.",
      trigger: "interact",
      interactEvent: "click",
      repeatCount: 3,
      skipPopup: true,
    },
    {
      id: "zoom-in",
      targetSelector: '[data-tutorial="zoom-in"]',
      instruction: "Now click the zoom-in button once.",
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
    {
      id: "zoom-reset",
      targetSelector: '[data-tutorial="zoom-reset"]',
      instruction: "Click the reset button to go back to 100% zoom.",
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
    {
      id: "pan-canvas",
      targetSelector: '[data-tutorial="canvas"]',
      instruction: "Drag the empty canvas area to pan the background around.",
      trigger: "interact",
      interactEvent: "fs-viewport-moved",
      delayMs: 1000,
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "lock-canvas",
      targetSelector: '[data-tutorial="lock-canvas"]',
      instruction: "Click the lock button to lock the canvas.",
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
    },
    {
      id: "try-pan-locked",
      targetSelector: '[data-tutorial="canvas"]',
      instruction:
        "Try to drag the canvas again — panning is now disabled because the canvas is locked.",
      trigger: "interact",
      interactEvent: "pointerup",
      delayMs: 1000,
      skipPopup: true,
      highlightBetween: PANEL_HIGHLIGHT,
      highlightTopOffset: 60,
    },
    {
      id: "export-json",
      targetSelector: '[data-tutorial="export"]',
      instruction:
        "Click Export and save the JSON file somewhere on your computer (you'll import it back in a moment).",
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "open-sidebar",
      targetSelector: '[data-tutorial="app-logo"]',
      instruction: "Click the FlowSpace logo in the top bar to open the side menu.",
      trigger: "interact",
      interactEvent: "click",
      delayMs: 500,
      skipPopup: true,
    },
    {
      id: "open-profile",
      targetSelector: '[data-tutorial="nav-profile"]',
      instruction: 'Now pick "Profile" from the menu to manage your saved systems.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
    },
    {
      id: "import-system",
      targetSelector: '[data-tutorial="import-system"]',
      instruction: 'Click "Import system" and pick the JSON file you just exported.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1500,
      skipPopup: true,
    },
    {
      id: "open-imported-system",
      targetSelector: '[data-tutorial="open-imported-system"]',
      instruction:
        'Your system appeared in the list. Click "Open in Lab" on it to load it back into the workspace.',
      trigger: "interact",
      interactEvent: "click",
      delayMs: 1000,
      skipPopup: true,
      highlightSelector: '[data-tutorial="imported-system-card"]',
    },
    {
      id: "finish-lesson",
      targetSelector: '[data-tutorial="finish-lesson"]',
      instruction: 'Click "Finish lesson" to complete this lesson.',
      trigger: "interact",
      interactEvent: "click",
      skipPopup: true,
      noHighlight: true,
      popupPlacement: "top",
    },
  ],
};

export const TUTORIAL_LESSONS: TutorialLesson[] = [
  SIMULATION_LESSON,
  EDITOR_LESSON,
  WORKSPACE_LESSON,
];
